
POST https://localhost:5001/api/Address/post
Content-Type: application/json

{
    "Street": "TESTE",
    "Number": 159,
    "Neighborhood": "TESTE2",
    "City": "TESTE",
    "CEP": "8745267-78"
}

### get all addresses 
GET https://localhost:5001/api/Address/getAll


### search by ID or NAME, but it's not searching
GET https://localhost:5001/api/Address/getByStreet/Equador

### update an existing address by ID 
PUT https://localhost:5001/api/Address/put/4
Content-Type: application/json

{ 
    "Street": "TESTE",
    "Number": 15,
    "Neighborhood": "AAA",
    "City": "AAAA",
    "CEP": "2222"
}


### deletion of a address by ID
DELETE https://localhost:5001/api/Address/delete/4