### Criação de uma nova categoria
POST https://localhost:5001/api/product/post
Content-Type: application/json

{
    "Name": "AAA",
    "Description": "AAA",
    "Code": "AAA",
    "UnitPrice": 3.2,
    "Amount": 3,
    "ProductCategoryId": 
}

### Obtenção de todas as categorias
GET https://localhost:5001/api/Product/getAll

### Obtenção de uma categoria específica pelo ID (substitua {id} pelo ID real)
GET https://localhost:5001/api/product/getByName/C

### Atualização de uma categoria existente pelo ID (substitua {id} pelo ID real)
PUT https://localhost:5001/api/product/put/5
Content-Type: application/json

{
    "Name": "Cini de Framboesa",
    "Description": "Refri"
}

### Exclusão de uma categoria pelo ID (substitua {id} pelo ID real)
DELETE https://localhost:5001/api/product/delete/3