### create of a service
POST https://localhost:5001/api/Service/post
Content-Type: application/json

{
    "Name": "Banho",
    "Description": "AAAA",
    "Code": "0202",
    "UnitPrice": 100.00
}

### all services 
GET https://localhost:5001/api/Service/getAll

###search by name
GET https://localhost:5001/api/Service/getByName/Banho

### update an existing service by ID 
PUT https://localhost:5001/api/Service/put/3
Content-Type: application/json

{
    "Name": "Tosa",
    "Description": "Tosa no animal",
    "Code": "0101",
    "UnitPrice": 250.00
}

### deletion of a service by ID
DELETE https://localhost:5001/api/Service/delete/3