POST https://localhost:5001/api/Timeline/post
Content-Type: application/json

{
    "CustomerId": 4,
    "AnimalId": 4,
    "ServiceId": 3,
    "EmployeeId": 3,
    "StartDate": "10/10/2023 14:30:00",
    "EndDate": "10/10/2023 16:45:00"

}

### get all Customer 
GET https://localhost:5001/api/Timeline/getAll


### search by ID or NAME, but it's not searching
GET https://localhost:5001/api/Timeline/getById/1

### update an existing Customer by ID 
PUT https://localhost:5001/api/Timeline/put/1
Content-Type: application/json

{
    "CustomerId": 2,
    "AnimalId": 1,
    "ServiceId": 1
}



### deletion of a Customer by ID
DELETE https://localhost:5001/api/Supplier/delete/1