POST https://localhost:5001/api/Timeline/post
Content-Type: application/json

{
    "CustomerId": 3,
    "AnimalId": 4,
    "ServiceId": 1,
    "EmployeeId": 2,
    "StartDate": "2023-10-12T18:00",
    "EndDate": "2023-10-12T18:31"
    //ano-mes-dia-T(tempo)-hora-minuto-segundo-mile.

}

### get all Customer 
GET https://localhost:5001/api/Timeline/getAll

### search by ID or NAME, but it's not searching
GET https://localhost:5001/api/Timeline/getById/11

### update an existing Customer by ID 
PUT https://localhost:5001/api/Timeline/put/11
Content-Type: application/json

{
    "CustomerId": 1,
    "AnimalId": 1,
    "ServiceId": 1,
    "EmployeeId": 1,
    "StartDate": "2023-10-12T18:00",
    "EndDate": "2023-10-12T18:40"
    //ano-mes-dia-T(tempo)-hora-minuto-segundo-mile.

}

### deletion of a Customer by ID
DELETE https://localhost:5001/api/Timeline/delete/7